[package]
name = "yuzu_lang"
version = "0.0.0"
edition = "2024"

[dependencies]
melior = { version = "0.27.6", features = ["ods-dialects"] }
yuzu_ast = { path = "../yuzu_ast" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_mlir = { path = "../yuzu_mlir" }
yuzu_parser = { path = "../yuzu_parser" }

[dev-dependencies]
expect-test = "1.5.0"
