[package]
name = "yuzu_passes"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
rustc-hash = "2"
melior = { version = "0.28.2", features = ["ods-dialects"] }
text-size = "1.1.1"
yuzu_ast = { path = "../yuzu_ast" }
yuzu_parser = { path = "../yuzu_parser" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_mlir = { path = "../yuzu_mlir" }
yuzu_syntax = { path = "../yuzu_syntax" }

[dev-dependencies]
expect-test = "1.5.0"

[lints]
workspace = true
