[package]
name = "yuzu_passes"
version = "0.0.0"
edition = "2024"

[dependencies]
rustc-hash = "2"
melior = { version = "0.27.6", features = ["ods-dialects"] }
text-size = "1.1.1"
yuzu_ast = { path = "../yuzu_ast" }
yuzu_parser = { path = "../yuzu_parser" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_mlir = { path = "../yuzu_mlir" }
yuzu_syntax = { path = "../yuzu_syntax" }
yuzu_types = { path = "../yuzu_types" }

[dev-dependencies]
expect-test = "1.5.0"
