# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "CompileError",
    "CompileOptions",
    "compile",
]

class CompileError(builtins.ValueError):
    r"""
    A compile that failed: the program, or the target it names. The message says why.
    """
    ...

@typing.final
class CompileOptions:
    @property
    def target(self) -> typing.Optional[builtins.str]:
        r"""
        The engine to compile for; `datafusion` when it is `None`.
        """
    def __new__(cls, target: typing.Optional[builtins.str] = None) -> CompileOptions: ...

def compile(source: builtins.str, options: typing.Optional[CompileOptions] = None) -> bytes:
    r"""
    Compile Yuzu source to a Substrait plan, returned as protobuf bytes.
    """

