[package]
name = "yuzu_substrait"
version = "0.0.0"
edition = "2024"

[dependencies]
rustc-hash = "2"
melior = { version = "0.28.2", features = ["ods-dialects"] }
prost = "0.14"
serde_json = "1"
substrait = { version = "0.63", features = ["serde"] }

yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_mlir = { path = "../yuzu_mlir" }
yuzu_types = { path = "../yuzu_types" }

[dev-dependencies]
expect-test = "1"
yuzu_ast = { path = "../yuzu_ast" }
yuzu_parser = { path = "../yuzu_parser" }
yuzu_passes = { path = "../yuzu_passes" }
