[package]
name = "yuzu_driver"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "yuzu"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
melior = { version = "0.28.2", features = ["ods-dialects"] }
rustc-hash = "2"
text-size = "1.1.1"

yuzu_ast = { path = "../yuzu_ast" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_mlir = { path = "../yuzu_mlir" }
yuzu_parser = { path = "../yuzu_parser" }
yuzu_passes = { path = "../yuzu_passes" }
yuzu_substrait = { path = "../yuzu_substrait" }
yuzu_syntax = { path = "../yuzu_syntax" }

[dev-dependencies]
expect-test = "1.5.1"

[lints]
workspace = true
