[package]
name = "yuzu_ast"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
yuzu_syntax = { path = "../yuzu_syntax" }

[dev-dependencies]
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_parser = { path = "../yuzu_parser" }

[lints]
workspace = true
