//! Typed borrowed views of dialect operations, generated by build.rs from
//! the TableGen definitions in yuzu_mlir_sys.
//!
//! melior's generated dialect enums (`YzlDialectOperation` and friends)
//! consume owned operations; a pass walks borrowed refs, so matching
//! happens here instead. Per dialect, one view struct per op with an
//! accessor per ODS argument (`yzl::WhereOp`), and an enum over
//! them for match-based dispatch (`yzl::YzlOp`). Delete this
//! module and build.rs when melior grows borrowing conversions upstream.

include!(concat!(env!("OUT_DIR"), "/ops.rs"));
