//! Typed, borrowed views of the dialects' operations, generated by build.rs
//! from the TableGen definitions in yuzu_mlir_sys.
//!
//! Each dialect has one view struct per op, with an accessor per ODS
//! argument (`yzl::WhereOp`), and an enum over them to match on
//! (`yzl::YzlOp`). A view borrows the operation, so a pass matches the ops
//! it walks without taking ownership of them.

include!(concat!(env!("OUT_DIR"), "/ops.rs"));

impl yzl::FnOp<'_, '_> {
    /// Whether the function is one the engine provides, with no body.
    pub fn is_external(&self) -> bool {
        self.external_name().is_some()
    }
}
