[package]
name = "yuzu_anf"
version = "0.0.0"
edition = "2024"

[dependencies]
id-arena = "2.3.0"
rustc-hash = "2"
string-interner = "0.20.0"

yuzu_anf_derive = { path = "../yuzu_anf_derive" }
yuzu_core = { path = "../yuzu_core" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_hir = { path = "../yuzu_hir" }
yuzu_syntax = { path = "../yuzu_syntax" }
yuzu_types = { path = "../yuzu_types" }

[dev-dependencies]
expect-test = "1.5.1"
yuzu_ast = { path = "../yuzu_ast" }
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_parser = { path = "../yuzu_parser" }
