//! Generates borrowed, typed op views from the `TableGen` dialect definitions.
//!
//! `llvm-tblgen --dump-json` reads the same `.td` files that melior's
//! `dialect!` macro and the C++ build consume, so the `TableGen` stays the
//! single source of truth: adding an op there materializes its kind-enum
//! variant, its typed view struct, and its accessors on the next build.
//!
//! melior's generated conversions (`TryFrom<Operation>`) consume owned
//! operations and are unusable from walks, which only hand out borrows.
//! This generation exists until melior grows borrowing conversions; when
//! that lands upstream, delete this file and the `ops` module with it.

use serde_json::Value as Json;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

struct Dialect {
    tblgen_prefix: &'static str,
    mlir_namespace: &'static str,
}

const DIALECTS: [Dialect; 3] = [
    Dialect {
        tblgen_prefix: "Yzl",
        mlir_namespace: "yzl",
    },
    Dialect {
        tblgen_prefix: "Yz",
        mlir_namespace: "yz",
    },
    Dialect {
        tblgen_prefix: "Yzr",
        mlir_namespace: "yzr",
    },
];

enum Arg {
    Operand {
        name: String,
        variadic: bool,
    },

    Attr {
        name: String,
        storage: Storage,
        optional: bool,
    },
}

/// ODS `storageType`s mapped to melior attribute wrappers — every wrapper
/// melior has. A storage type melior cannot wrap reads as a plain
/// `Attribute` (with a build warning), so a new attribute kind in the
/// `TableGen` never breaks the build; it just reads untyped until melior
/// grows a wrapper for it.
#[derive(Clone, Copy)]
enum Storage {
    /// Converted into the named melior wrapper.
    Wrapped(&'static str),
    /// A storage type melior has no wrapper for: read raw.
    Other,
    /// `UnitAttr`: presence, read as bool.
    Unit,
}

impl Storage {
    fn from_ods(storage: &str) -> Self {
        match storage.trim().trim_start_matches("::") {
            "mlir::StringAttr" => Self::Wrapped("StringAttribute"),
            "mlir::FlatSymbolRefAttr" => Self::Wrapped("FlatSymbolRefAttribute"),
            "mlir::BoolAttr" => Self::Wrapped("BoolAttribute"),
            "mlir::FloatAttr" => Self::Wrapped("FloatAttribute"),
            "mlir::IntegerAttr" => Self::Wrapped("IntegerAttribute"),
            "mlir::TypeAttr" => Self::Wrapped("TypeAttribute"),
            "mlir::DenseI32ArrayAttr" => Self::Wrapped("DenseI32ArrayAttribute"),
            "mlir::DenseI64ArrayAttr" => Self::Wrapped("DenseI64ArrayAttribute"),
            "mlir::DenseElementsAttr"
            | "mlir::DenseIntElementsAttr"
            | "mlir::DenseFPElementsAttr" => Self::Wrapped("DenseElementsAttribute"),
            "mlir::DictionaryAttr" => Self::Wrapped("DictionaryAttribute"),
            "mlir::StridedLayoutAttr" => Self::Wrapped("StridedLayoutAttribute"),
            "mlir::ArrayAttr" => Self::Wrapped("ArrayAttribute"),
            "mlir::UnitAttr" => Self::Unit,
            other => {
                println!(
                    "cargo:warning=melior has no wrapper for `{other}`: its accessor reads a plain Attribute"
                );
                Self::Other
            }
        }
    }

    fn wrapper(self) -> &'static str {
        match self {
            Self::Wrapped(wrapper) => wrapper,
            Self::Other => "Attribute",
            Self::Unit => unreachable!("unit attributes read as presence, not values"),
        }
    }

    fn is_raw(self) -> bool {
        matches!(self, Self::Other)
    }
}

/// Attributes the crate gives a type of its own. The generator leaves the
/// accessor out so a hand-written one of the same name stands in its place,
/// reading the attribute back as what it means rather than what it stores.
/// Every entry is checked against the dialect, so renaming one in `TableGen`
/// fails the build rather than silently leaving two accessors or none.
const TYPED_ACCESSORS: &[(&str, &str)] = &[
    ("yzl.call", "callee_source"),
    ("yz.cmp", "predicate"),
    ("yzl.join", "kind"),
    ("yzr.join", "kind"),
];

struct Op {
    /// The MLIR name, e.g. `yzl.where`.
    full_name: String,
    /// The enum variant, e.g. `Where`.
    variant: String,
    args: Vec<Arg>,
    regions: Vec<String>,
    results: Vec<String>,
}

fn main() {
    let llvm = PathBuf::from(env::var("MLIR_SYS_230_PREFIX").expect("MLIR_SYS_230_PREFIX is set"));
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let cpp = manifest.join("../yuzu_mlir_sys/cpp");

    let mut generated = String::from(
        "// Generated by build.rs from the TableGen files in yuzu_mlir_sys. Do not edit.\n",
    );
    let mut declared = Vec::new();
    for dialect in DIALECTS {
        let ops = parse_dialect(&llvm, &cpp, &dialect);
        for op in &ops {
            for arg in &op.args {
                if let Arg::Attr { name, .. } = arg {
                    declared.push((
                        op.full_name.clone(),
                        name.trim_start_matches("r#").to_string(),
                    ));
                }
            }
        }

        generate_typed_module(&mut generated, &dialect, &ops);
    }

    for (op, attribute) in TYPED_ACCESSORS {
        assert!(
            declared
                .iter()
                .any(|(name, arg)| name == op && arg == attribute),
            "`{op}` has no `{attribute}` attribute to give a type of its own"
        );
    }

    println!("cargo:rerun-if-changed={}", cpp.display());
    println!("cargo:rerun-if-env-changed=MLIR_SYS_230_PREFIX");
    fs::write(out.join("ops.rs"), generated).expect("the generated ops file writes");
}

fn parse_dialect(llvm: &Path, cpp: &Path, dialect: &Dialect) -> Vec<Op> {
    let output = Command::new(llvm.join("bin/llvm-tblgen"))
        .arg("--dump-json")
        .arg(cpp.join(format!("{}Dialect.td", dialect.tblgen_prefix)))
        .arg("-I")
        .arg(llvm.join("include"))
        .output()
        .expect("llvm-tblgen runs");
    assert!(
        output.status.success(),
        "llvm-tblgen --dump-json failed for {}: {}",
        dialect.tblgen_prefix,
        String::from_utf8_lossy(&output.stderr)
    );
    let records: Json = serde_json::from_slice(&output.stdout).expect("tblgen emits valid JSON");
    let records = records.as_object().expect("the record keeper is an object");

    let dialect_def = format!("{}_Dialect", dialect.tblgen_prefix);
    let mut ops = Vec::new();
    for (def_name, record) in records {
        if !superclasses(record).any(|class| class == "Op") {
            continue;
        }

        let Some(op_name) = record["opName"].as_str().filter(|name| !name.is_empty()) else {
            continue;
        };

        if record["opDialect"]["def"].as_str() != Some(&dialect_def) {
            continue;
        }

        let variant = def_name
            .strip_prefix(&format!("{}_", dialect.tblgen_prefix))
            .and_then(|name| name.strip_suffix("Op"))
            .unwrap_or_else(|| {
                panic!(
                    "op def `{def_name}` is not named `{}_<Name>Op`",
                    dialect.tblgen_prefix
                )
            });

        let full_name = format!("{}.{op_name}", dialect.mlir_namespace);
        let args: Vec<Arg> = dag_args(&record["arguments"])
            .map(|(constraint, name)| {
                let constraint = &records[constraint];
                if superclasses(constraint).any(|class| class == "Attr") {
                    Arg::Attr {
                        name,
                        storage: Storage::from_ods(constraint["storageType"].as_str().unwrap()),
                        optional: constraint["isOptional"].as_i64() == Some(1),
                    }
                } else {
                    Arg::Operand {
                        name,
                        variadic: superclasses(constraint).any(|class| class == "Variadic"),
                    }
                }
            })
            .collect();
        let regions: Vec<String> = dag_args(&record["regions"])
            .map(|(constraint, name)| {
                assert!(
                    !superclasses(&records[constraint]).any(|class| class == "VariadicRegion"),
                    "`{full_name}` has a variadic region: the generated index scheme cannot represent it"
                );
                name
            })
            .collect();
        let results: Vec<String> = dag_args(&record["results"])
            .map(|(constraint, name)| {
                assert!(
                    !superclasses(&records[constraint]).any(|class| class == "Variadic"),
                    "`{full_name}` has a variadic result: the generated index scheme cannot represent it"
                );
                name
            })
            .collect();

        // The variadic accessor reads every operand from its start index on,
        // which is only right when nothing follows it.
        if let Some(index) = args
            .iter()
            .position(|arg| matches!(arg, Arg::Operand { variadic: true, .. }))
        {
            assert!(
                args[index + 1..]
                    .iter()
                    .all(|arg| !matches!(arg, Arg::Operand { .. })),
                "`{full_name}` has an operand after its variadic: the generated index scheme cannot represent it"
            );
        }

        let mut accessors = std::collections::BTreeSet::from(["of", "operation"]);
        for name in args
            .iter()
            .map(|arg| match arg {
                Arg::Operand { name, .. } | Arg::Attr { name, .. } => name.as_str(),
            })
            .chain(regions.iter().map(String::as_str))
            .chain(results.iter().map(String::as_str))
        {
            assert!(
                accessors.insert(name),
                "`{full_name}` argument `{name}` collides with another accessor"
            );
        }

        ops.push(Op {
            full_name,
            variant: variant.to_string(),
            args,
            regions,
            results,
        });
    }

    assert!(
        !ops.is_empty(),
        "no ops found for dialect {}",
        dialect.tblgen_prefix
    );
    ops
}

fn superclasses(record: &Json) -> impl Iterator<Item = &str> {
    record["!superclasses"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Json::as_str)
}

fn dag_args(dag: &Json) -> impl Iterator<Item = (&str, String)> {
    dag["args"].as_array().into_iter().flatten().map(|pair| {
        let constraint = pair[0]["def"].as_str().expect("dag arguments name a def");
        let name = pair[1].as_str().expect("dag arguments are named");
        (constraint, escape(name))
    })
}

fn escape(name: &str) -> String {
    // The keywords that cannot even be raw-escaped as method names.
    const UNUSABLE: [&str; 4] = ["crate", "self", "super", "Self"];
    const KEYWORDS: [&str; 35] = [
        "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "extern",
        "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut",
        "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use",
        "where", "while", "yield",
    ];
    assert!(
        !UNUSABLE.contains(&name),
        "ODS argument name `{name}` cannot be a Rust method name"
    );
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// The typed views: one borrowing struct per op with accessors named after
/// the ODS arguments, and an enum over them for match-based dispatch.
fn generate_typed_module(out: &mut String, dialect: &Dialect, ops: &[Op]) {
    let enum_name = format!("{}Op", dialect.tblgen_prefix);
    writeln!(
        out,
        "\n/// Borrowed, typed views of `{}` operations.",
        dialect.mlir_namespace
    )
    .unwrap();
    writeln!(out, "pub mod {} {{", dialect.mlir_namespace).unwrap();
    write_imports(out, ops);

    for op in ops {
        generate_struct(out, op);
    }

    writeln!(
        out,
        "\n    /// A typed view of any `{}` operation.",
        dialect.mlir_namespace
    )
    .unwrap();
    writeln!(out, "    #[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(out, "    pub enum {enum_name}<'c, 'a> {{").unwrap();
    for op in ops {
        writeln!(out, "        {}({}Op<'c, 'a>),", op.variant, op.variant).unwrap();
    }

    writeln!(out, "    }}\n").unwrap();

    writeln!(out, "    impl<'c, 'a> {enum_name}<'c, 'a> {{").unwrap();
    writeln!(
        out,
        "        /// Reached through `OperationCast`, which is how a pass asks."
    )
    .unwrap();
    writeln!(
        out,
        "        pub(crate) fn of(operation: &'a Operation<'c>) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "            Some(match operation.name().as_string_ref().as_str().ok()? {{"
    )
    .unwrap();
    for op in ops {
        writeln!(
            out,
            "                \"{}\" => Self::{}({}Op {{ operation }}),",
            op.full_name, op.variant, op.variant
        )
        .unwrap();
    }

    writeln!(out, "                _ => return None,").unwrap();
    writeln!(out, "            }})").unwrap();
    writeln!(out, "        }}\n").unwrap();
    writeln!(out, "        #[must_use]").unwrap();
    writeln!(
        out,
        "        pub fn operation(&self) -> &'a Operation<'c> {{"
    )
    .unwrap();
    writeln!(out, "            match self {{").unwrap();
    for op in ops {
        writeln!(
            out,
            "                Self::{}(op) => op.operation,",
            op.variant
        )
        .unwrap();
    }

    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

fn write_imports(out: &mut String, ops: &[Op]) {
    let mut attributes = std::collections::BTreeSet::new();
    let mut ir = std::collections::BTreeSet::from(["Operation", "OperationLike"]);
    for op in ops {
        for arg in &op.args {
            match arg {
                Arg::Operand { .. } => {
                    ir.insert("Value");
                }
                Arg::Attr {
                    storage: Storage::Unit,
                    ..
                } => {}

                Arg::Attr { storage, .. } if storage.is_raw() => {
                    ir.insert("Attribute");
                }
                Arg::Attr { storage, .. } => {
                    attributes.insert(storage.wrapper());
                }
            }
        }

        if !op.regions.is_empty() {
            ir.insert("RegionRef");
        }

        if !op.results.is_empty() {
            ir.insert("OperationResult");
        }
    }

    if !attributes.is_empty() {
        let list = attributes.into_iter().collect::<Vec<_>>().join(", ");
        writeln!(out, "    use melior::ir::attribute::{{{list}}};").unwrap();
    }

    let mut operation = vec!["Operation", "OperationLike"];
    if ir.remove("OperationResult") {
        operation.push("OperationResult");
    }

    ir.remove("Operation");
    ir.remove("OperationLike");
    writeln!(
        out,
        "    use melior::ir::operation::{{{}}};",
        operation.join(", ")
    )
    .unwrap();
    if !ir.is_empty() {
        let list = ir.into_iter().collect::<Vec<_>>().join(", ");
        writeln!(out, "    use melior::ir::{{{list}}};").unwrap();
    }
}

fn generate_struct(out: &mut String, op: &Op) {
    let name = format!("{}Op", op.variant);
    writeln!(out, "\n    /// A borrowed `{}` operation.", op.full_name).unwrap();
    writeln!(out, "    #[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(out, "    pub struct {name}<'c, 'a> {{").unwrap();
    writeln!(out, "        operation: &'a Operation<'c>,").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(out, "    impl<'c, 'a> {name}<'c, 'a> {{").unwrap();
    writeln!(
        out,
        "        pub const NAME: &'static str = \"{}\";\n",
        op.full_name
    )
    .unwrap();
    writeln!(out, "        #[must_use]").unwrap();
    writeln!(
        out,
        "        pub fn of(operation: &'a Operation<'c>) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "            (operation.name().as_string_ref().as_str() == Ok(Self::NAME))"
    )
    .unwrap();
    writeln!(out, "                .then_some(Self {{ operation }})").unwrap();
    writeln!(out, "        }}\n").unwrap();
    writeln!(out, "        #[must_use]").unwrap();
    writeln!(
        out,
        "        pub fn operation(&self) -> &'a Operation<'c> {{"
    )
    .unwrap();
    writeln!(out, "            self.operation").unwrap();
    writeln!(out, "        }}").unwrap();

    let mut operand_index = 0;
    for arg in &op.args {
        match arg {
            Arg::Operand {
                name: arg_name,
                variadic: false,
            } => {
                writeln!(out, "\n        /// The `{arg_name}` operand.").unwrap();
                writeln!(out, "        ///\n        /// # Panics\n        ///\n        /// Panics if the op does not verify: a verified op always has it.").unwrap();
                writeln!(out, "        #[must_use]").unwrap();
                writeln!(out, "        pub fn {arg_name}(&self) -> Value<'c, 'a> {{").unwrap();
                writeln!(
                    out,
                    "            self.operation.operand({operand_index}).expect(\"`{}` has a `{arg_name}` operand\")",
                    op.full_name
                )
                .unwrap();
                writeln!(out, "        }}").unwrap();
                operand_index += 1;
            }
            Arg::Operand {
                name: arg_name,
                variadic: true,
            } => {
                writeln!(out, "\n        /// The `{arg_name}` operands.").unwrap();
                writeln!(
                    out,
                    "        pub fn {arg_name}(&self) -> impl Iterator<Item = Value<'c, 'a>> {{"
                )
                .unwrap();
                if operand_index == 0 {
                    writeln!(out, "            self.operation.operands()").unwrap();
                } else {
                    writeln!(
                        out,
                        "            self.operation.operands().skip({operand_index})"
                    )
                    .unwrap();
                }
                writeln!(out, "        }}").unwrap();
            }
            Arg::Attr {
                name: arg_name,
                storage: Storage::Unit,
                ..
            } => {
                let raw = arg_name.trim_start_matches("r#");
                writeln!(
                    out,
                    "\n        /// Whether the `{raw}` unit attribute is present."
                )
                .unwrap();
                writeln!(out, "        #[must_use]").unwrap();
                writeln!(out, "        pub fn {arg_name}(&self) -> bool {{").unwrap();
                writeln!(
                    out,
                    "            self.operation.attribute(\"{raw}\").is_ok()"
                )
                .unwrap();
                writeln!(out, "        }}").unwrap();
            }
            Arg::Attr {
                name: arg_name,
                storage,
                optional,
            } => {
                let raw = arg_name.trim_start_matches("r#");
                if TYPED_ACCESSORS.contains(&(op.full_name.as_str(), raw)) {
                    continue;
                }

                let wrapper = storage.wrapper();
                let note = match storage {
                    Storage::Other => " Raw: melior has no wrapper for its storage type.",
                    _ => "",
                };
                writeln!(out, "\n        /// The `{raw}` attribute.{note}").unwrap();
                // Only an optional attribute kept raw is read without `expect`.
                if !(*optional && storage.is_raw()) {
                    writeln!(out, "        ///\n        /// # Panics\n        ///\n        /// Panics if the op does not verify: a verified op always has it.").unwrap();
                }
                if *optional {
                    writeln!(out, "        #[must_use]").unwrap();
                    writeln!(
                        out,
                        "        pub fn {arg_name}(&self) -> Option<{wrapper}<'c>> {{"
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "            let attribute = self.operation.attribute(\"{raw}\").ok()?;"
                    )
                    .unwrap();
                    if storage.is_raw() {
                        writeln!(out, "            Some(attribute)").unwrap();
                    } else {
                        writeln!(
                            out,
                            "            Some(attribute.try_into().expect(\"`{raw}` on `{}` is {}\"))",
                            op.full_name,
                            article(wrapper)
                        )
                        .unwrap();
                    }
                    writeln!(out, "        }}").unwrap();
                } else if storage.is_raw() {
                    writeln!(out, "        #[must_use]").unwrap();
                    writeln!(out, "        pub fn {arg_name}(&self) -> {wrapper}<'c> {{").unwrap();
                    writeln!(out, "            self.operation").unwrap();
                    writeln!(out, "                .attribute(\"{raw}\")").unwrap();
                    writeln!(
                        out,
                        "                .expect(\"`{}` has a `{raw}` attribute\")",
                        op.full_name
                    )
                    .unwrap();
                    writeln!(out, "        }}").unwrap();
                } else {
                    writeln!(out, "        #[must_use]").unwrap();
                    writeln!(out, "        pub fn {arg_name}(&self) -> {wrapper}<'c> {{").unwrap();
                    writeln!(out, "            let attribute = self.operation").unwrap();
                    writeln!(out, "                .attribute(\"{raw}\")").unwrap();
                    writeln!(
                        out,
                        "                .expect(\"`{}` has a `{raw}` attribute\");",
                        op.full_name
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "            attribute.try_into().expect(\"`{raw}` on `{}` is {}\")",
                        op.full_name,
                        article(wrapper)
                    )
                    .unwrap();
                    writeln!(out, "        }}").unwrap();
                }
            }
        }
    }

    for (index, region) in op.regions.iter().enumerate() {
        writeln!(out, "\n        /// The `{region}` region.").unwrap();
        writeln!(out, "        ///\n        /// # Panics\n        ///\n        /// Panics if the op does not verify: a verified op always has it.").unwrap();
        writeln!(out, "        #[must_use]").unwrap();
        writeln!(
            out,
            "        pub fn {region}(&self) -> RegionRef<'c, 'a> {{"
        )
        .unwrap();
        writeln!(
            out,
            "            self.operation.region({index}).expect(\"`{}` has a `{region}` region\")",
            op.full_name
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    }

    for (index, result) in op.results.iter().enumerate() {
        writeln!(out, "\n        /// The `{result}` result.").unwrap();
        writeln!(out, "        ///\n        /// # Panics\n        ///\n        /// Panics if the op does not verify: a verified op always has it.").unwrap();
        writeln!(out, "        #[must_use]").unwrap();
        writeln!(
            out,
            "        pub fn {result}(&self) -> OperationResult<'c, 'a> {{"
        )
        .unwrap();
        writeln!(
            out,
            "            self.operation.result({index}).expect(\"`{}` has a `{result}` result\")",
            op.full_name
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    }

    writeln!(out, "    }}").unwrap();
}

fn article(wrapper: &str) -> String {
    match wrapper.chars().next() {
        Some('A' | 'E' | 'I' | 'O' | 'U') => format!("an {wrapper}"),
        _ => format!("a {wrapper}"),
    }
}
